sudo: required
dist: trusty
language: node_js
node_js:
  - 12.12.0

# addons:
#  chrome: stable
cache:
  directories:
  - $HOME/.npm

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install codecov -g
  - npm ci

script: 
  - npm run ci
  - bash ./.travis-deploy.sh

after_success:
  - codecov