environment:
  matrix:
  - nodejs_version: "11.10.1"

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm run ci

build: off